DROP DATABASE IF EXISTS hedb ;
CREATE DATABASE mybatisdb CHARACTER SET UTF8 ;
USE mybatisdb ;
DROP TABLE IF EXISTS member;
CREATE TABLE member (
	mid			VARCHAR(50) ,
	name		VARCHAR(50) ,
	age			INT ,
	school  	VARCHAR(50) ,
	score		DOUBLE ,
	company		VARCHAR(50) ,
	salary		DOUBLE ,
	flag		VARCHAR(50) ,
	CONSTRAINT pk_mid PRIMARY KEY(mid)
) ;


DROP TABLE IF EXISTS MEMBER_DETAILS;
DROP TABLE IF EXISTS MEMBER_LOGIN;
-- 创建数据表
CREATE TABLE MEMBER_LOGIN (
	MID			VARCHAR(50) ,
	PASSWORD		VARCHAR(50) ,
	CONSTRAINT PK_MID PRIMARY KEY(MID)
) ;
CREATE TABLE MEMBER_DETAILS (
	MID			VARCHAR(50) ,
	NAME		VARCHAR(50) ,
	AGE			INT ,
	CONSTRAINT PK_MID2 PRIMARY KEY(MID) ,
	CONSTRAINT FK_MID FOREIGN KEY(MID) REFERENCES MEMBER_LOGIN(MID) ON DELETE CASCADE			
) ;