server:
  port: 80

spring:
  application:
    name: service-salesmanagement
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode\=true&characterEncoding\=utf-8
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true